spring.application.name=clinic-api
spring.datasource.url=jdbc:mysql://localhost:3306/clinicapi
spring.datasource.username=root
spring.datasource.password=rocha@@789_
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false