CREATE TABLE patients (
    id    BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name  VARCHAR(150) NOT NULL,
    email VARCHAR(150) NOT NULL,
    phone VARCHAR(20)  NOT NULL,
    cpf   VARCHAR(11)  NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE doctors (
    id        BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    name      VARCHAR(150) NOT NULL,
    email     VARCHAR(150) NOT NULL,
    phone     VARCHAR(20)  NOT NULL,
    crm       VARCHAR(20)  NOT NULL,
    specialty VARCHAR(30)  NOT NULL,
    active    BOOLEAN      NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE users (
    id       BIGINT       GENERATED BY DEFAULT AS IDENTITY,
    login    VARCHAR(150) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role     VARCHAR(20)  NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT uk_users_login UNIQUE (login)
);

CREATE TABLE appointments (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY,
    patient_id BIGINT      NOT NULL,
    doctor_id  BIGINT      NOT NULL,
    date_time  TIMESTAMP   NOT NULL,
    status     VARCHAR(20) NOT NULL,
    PRIMARY KEY (id),
    CONSTRAINT fk_appointments_patient FOREIGN KEY (patient_id) REFERENCES patients (id),
    CONSTRAINT fk_appointments_doctor  FOREIGN KEY (doctor_id)  REFERENCES doctors (id)
);